### ISSUE TITLE
"Unable to read beyond the end of the stream" when opening MySims Kingdom vault

### ISSUE THREAD

**Issue by StayFrozty** [Olivercomet/MorcuTool#1]
Hi there! My extracted files from MySims Kingdom have two vault files, and both of them throw an error upon trying to load them (see below).

This obviously makes it near impossible to extract the specific mdl file I'm after, as there are thousands, and I can't view them by name. Another cool alternative would be to either add the option to sort by extension, or add the option to extract all models.

Kind regards :)

> ************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at MorcuTool.Vault.LoadVault()
   at MorcuTool.Form1.loadVaultToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Olivercomet** [comment]
Hi,
Unfortunately the Kingdom vault files don't include the filenames, so implementing them wouldn't really do anything. Since textures are a bit easier to view in bulk, you could find a texture you know is used in the model and use the 'backtrack to model' feature. Or export the entire archive, sort by type in the windows file explorer, then copy those elsewhere and sort by filesize.

Hope this helps! :D
