### ISSUE TITLE
Another problem with Skyheroes models.

### ISSUE THREAD

**Issue by harrytheliar** [Olivercomet/MorcuTool#3]
Hello! I came across another problem. Some character models seem to extract fine and can be imported into blender, while some others aren't. I came across this problem with both Martin and Selena's models when I tried importing them into blender:

bpy.ops.object.select_all(action='SELECT')

bpy.ops.object.delete(use_global=False, confirm=False)

Deleted 3 object(s)

bpy.context.space_data.recent_folders_active = 0

Python: Traceback (most recent call last):
  File "G:\- Just some programs\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_obj\__init__.py", line 146, in execute
    return import_obj.load(context, **keywords)
  File "G:\- Just some programs\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_obj\import_obj.py", line 1264, in load
    for data in split_mesh(verts_loc, faces, unique_materials, filepath, SPLIT_OB_OR_GROUP):
  File "G:\- Just some programs\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_scene_obj\import_obj.py", line 547, in split_mesh
    verts_split.append(verts_loc[vert_idx])  # add the vert to the local verts
IndexError: list index out of range

location: <unknown location>:-1

**Comment by Olivercomet** [comment]
Hi! I may fix this when I have more time, but I am very busy this week.
From the error, it sounds like one of the number lists in the OBJ file starts at 0 when it should be starting at 1. So you might be able to temporarily correct this by opening the OBJ in notepad and changing any lone zeroes to ones. But even if it then loads, it might still be mangled if all the other numbers are still off by one. Strange that it's only happening with some models and not all of them.

**Comment by Olivercomet** [comment]
I'm afraid I've had a look and I'm not completely on top of how the models are stored anymore, so I'm not sure why these ones are exceptions. Sorry about that.

**Comment by harrytheliar** [comment]
I see... That's a shame. Thank you for trying and taking a look at least. :] Have a good day.
